name: Haskell CI

on:
  push:
    branches: [master, production]
  pull_request:
    branches: [master]

jobs:
  stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ["2.7.1"]
        ghc: ["8.10.4"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: "8.10.4" # Exact version of ghc to use
          enable-stack: true
          stack-version: "latest"

      - name: Install dependencies
        run: |
          stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

      - name: Build
        run: |
          stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

      - name: Test
        run: |
          stack test --system-ghc
